Document: scriptcoll
Title: Debian scriptcoll Manual
Author: b2f3t
Abstract: This manual describes what scriptcoll is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/scriptcoll/scriptcoll.sgml.gz

Format: postscript
Files: /usr/share/doc/scriptcoll/scriptcoll.ps.gz

Format: text
Files: /usr/share/doc/scriptcoll/scriptcoll.text.gz

Format: HTML
Index: /usr/share/doc/scriptcoll/html/index.html
Files: /usr/share/doc/scriptcoll/html/*.html
