#!/bin/bash
BASEDIR="/mnt"
TARGET="SAVES"
mkdir $TARGET
PARTITION=$1
MOUNTPOINT=$BASEDIR/`echo $PARTITION | egrep -o sd.[0-9]+`
mkdir -p $MOUNTPOINT
mount $PARTITION $MOUNTPOINT
if [ $? -eq 0 ] ; then
	cp -r $MOUNTPOINT $TARGET
    umount $PARTITION
    if [ $? -eq 0 ] ; then
    	rm -r $MOUNTPOINT
    fi
else
	rm -r $MOUNTPOINT
fi
exit 0
